export const LOAD_REPORTS_SUCCESS = "LOAD_REPORTS_SUCCESS";
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS";

export const SHOW_ALL = "SHOW_ALL";
export const SHOW_GENDER = "SHOW_GENDER";
export const SHOW_AGE_RANGE = "SHOW_AGE_RANGE";
export const SHOW_LOCATION = "SHOW_LOCATION";
export const SHOW_DEVICE_TYPE = "SHOW_DEVICE_TYPE";
export const SHOW_OPERATING_SYSTEM = "SHOW_OPERATING_SYSTEM";
export const SHOW_VISITORS = "SHOW_VISITORS";

export const SORT_ASC = "SORT_ASC";
export const SORT_DESC = "SORT_DESC";

export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const SET_VISIBILITY_SORT = "SET_VISIBILITY_SORT";
